### ISSUE TITLE
Compile error building package in Xcode 15.0 beta 

### ISSUE THREAD

**Issue by valeriyvan** [WeTransfer/WeScan#359]
`Stored properties cannot be marked unavailable with '@available'`

<img width="1006" alt="Screenshot 2023-06-19 at 16 59 00" src="https://github.com/WeTransfer/WeScan/assets/1630974/69d303d2-67d9-4db8-b38a-b417e148c412">

It should be marked se `deprecated` instead of `unavailable`.

**Comment by BasThomas** [comment]
Thanks for this, @valeriyvan! I wonder if we should remove them altogether, given that they've been renamed for a while — we can do a major release and mention this in the upgrade notes. What do you think?

**Comment by valeriyvan** [comment]
> Thanks for this, @valeriyvan! I wonder if we should remove them altogether, given that they've been renamed for a while — we can do a major release and mention this in the upgrade notes. What do you think?

Hi. It doesn't matter for me remove or fix properly deprecating. You better know as maintainer. What only matters for me - make project build.

**Comment by BasThomas** [comment]
I think we can go ahead and remove them :)

**Comment by valeriyvan** [comment]
Solved with #354

**Comment by BasThomas** [comment]
Thanks! Seems like we can consider cutting a new release now that we're ready for Xcode 15! Would you be interested in picking that up, @valeriyvan?

**Comment by BasThomas** [comment]
Gotcha, thanks for bringing it up! I'm going to take a look at that, and make sure to check with you before we cut a release!

**Comment by ayushineogov** [comment]
I am using this library with pods, and I am still facing this errors in Xcode 15 ,
I have tried with Package manager and working fine, 
Is there any solution for pods ?

**Comment by BasThomas** [comment]
No, we no longer support CocoaPods for our latest versions.
